### PR TITLE
Add module version

### PR DESCRIPTION
**Pull request by appsforartists**
Igor Minar discusses some common reasons for bundles to be needlessly large in [his ReactiveConf 2017 talk](https://www.youtube.com/watch?v=75ObMlqrhFY).  One common problem is having commonJS in your dependency tree.  Given the choice between adding a commonJS dependency or copy-pasting/reimplementing a 1-line function, I choose the latter.  I know I'm not alone.

This PR adds an equivalent implementation as a module, which will allow tools to better statically analyze this dependency and minimize the amount of bloat when it's included in a bundle.

It has rebased been rebased from #5.

### CODE REVIEW

**Comment by appsforartists** [comment]
Just rebased from HEAD

**Comment by sindresorhus** [comment]
Sorry, I'm not interested in adding lots of boilerplate for this. It's totally possible to statically analyze CommonJS as long as you're not doing something weird. Here we just have a `module.exports`. Bloat usually comes from Node.js built-in polyfills rather than depending on CommonJS dependencies. There's a lot of misinformation in this area.

**Comment by sindresorhus** [comment]
> Given the choice between adding a commonJS dependency or copy-pasting/reimplementing a 1-line function, I choose the latter. I know I'm not alone.

That's your choice, but you're going to have to do a lot of copy-paste.

**Comment by appsforartists** [comment]
That's too bad - it's just some `package.json` metadata and a second pass through the test suite - the actual logic of the function is the same.

**Pull request closed without merging**
