### PR TITLE
More correct check

### PR DESCRIPTION
**Pull request by kof**

### CODE REVIEW

**Comment by sindresorhus** [comment]
How is this more correct?

**Comment by appsforartists** [comment]
Pedantically, having a `$$observable` method doesn't mean that the object is an observable, just that it knows how to cast itself to one.  The result of calling `$$observable` is an observable; if the object returns itself when that method is called, it must be an observable.

For example, look at how the proposal describes[`Observable.from`](https://github.com/tc39/proposal-observable#observablefrom).

@kof opened this because he wants to replace the inline version of `isObservable` that I wrote in his repo with this package.  Unfortunately, the most important difference between the two implementations is that mine uses modules rather than commonJS.  I tried adding a module implementation in a PR, but I couldn't figure out how to make `ava` respect import statements.  `test` could `import` just fine, but if the module it imported had an `import`, it would throw.

Here's that WIP: 
https://github.com/appsforartists/is-observable/tree/esm

```
~/Projects/is-observable/index.module.js:1
(function (exports, require, module, __filename, __dirname) { import $$observable from 'symbol-observable';
                                                              ^^^^^^

SyntaxError: Unexpected token import
```

**Comment by sindresorhus** [comment]
I'm just paranoid that executing `value[symbolObservable]()` might have side-effects in some Observable libs/situtations.

**Comment by appsforartists** [comment]
Interesting.  This test comes from [a type guard I wrote](https://github.com/material-motion/material-motion-js/blob/6fe8c15e9261230c69559ecd939dc37d6072ee0a/packages/core/src/typeGuards.ts#L52) from spec for Material Motion ages ago.  Honestly, I hadn't considered that someone would have a side-effectful conversation method when I wrote it.

Can you think of a case where someone would plausibly want side effects in that method?  Intuitively, I'm more concerned about false positives (thinking something is an observable when it is just able to be cast to one) than I am about side effects in a getter.

**Comment by sindresorhus** [comment]
I can't think of any scenario. Let's merge and see. It will most likely be fine.

**Pull request merged**
